on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static site
        run: npm run build

      - name: Install LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy via LFTP
        run: |
          lftp -u "jakubjenik_cz,tempotegola" "ftp.jakubjenik.cz" <<EOF
          set ssl:verify-certificate no
          mirror -R --only-newer --dereference --continue --delete --verbose=3 --parallel=10 \
          ./out jakubjenik.cz
          EOF
