on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: LFTP rsync check
        run: |
          lftp -u "jakubjenik_cz","tempotegola" "ftp.jakubjenik.cz" <<EOF
          set ssl:verify-certificate no
          mirror -R --only-newer --dereference --continue --delete --verbose=3 --parallel=10 --exclude .git --exclude .github --exclude .README.md ./ jakubjenik.cz
          EOF
